/**
 * withSecureStoreXml.js
 *
 * Expo config plugin that creates the two XML resource files required by
 * expo-secure-store on Android. These files are referenced in AndroidManifest.xml
 * but are NOT auto-generated by the expo-secure-store config plugin in all
 * versions, causing the build error:
 *   resource xml/secure_store_data_extraction_rules not found
 *   resource xml/secure_store_backup_rules not found
 *
 * This plugin writes both files into android/app/src/main/res/xml/ during
 * every expo prebuild run so EAS CI always has them.
 */
const { withDangerousMod } = require('@expo/config-plugins');
const fs   = require('fs');
const path = require('path');

const BACKUP_RULES = `<?xml version="1.0" encoding="utf-8"?>
<!--
  Backup rules for expo-secure-store.
  Excludes all SecureStore entries from Android Auto Backup so that
  encrypted keystore-backed credentials are never synced to Google Drive.
-->
<full-backup-content>
  <exclude domain="sharedpref" path="SecureStore"/>
  <exclude domain="database" path="RNCrypto"/>
</full-backup-content>
`;

const EXTRACTION_RULES = `<?xml version="1.0" encoding="utf-8"?>
<!--
  Data extraction rules for expo-secure-store (Android 12+).
  Excludes SecureStore data from cloud backup and device-to-device transfer
  so that hardware keystore-backed secrets are never transferred.
-->
<data-extraction-rules>
  <cloud-backup>
    <exclude domain="sharedpref" path="SecureStore"/>
    <exclude domain="database" path="RNCrypto"/>
  </cloud-backup>
  <device-transfer>
    <exclude domain="sharedpref" path="SecureStore"/>
    <exclude domain="database" path="RNCrypto"/>
  </device-transfer>
</data-extraction-rules>
`;

module.exports = function withSecureStoreXml(config) {
  return withDangerousMod(config, [
    'android',
    async (mod) => {
      const xmlDir = path.join(
        mod.modRequest.platformProjectRoot,
        'app', 'src', 'main', 'res', 'xml',
      );

      // Ensure the res/xml directory exists
      if (!fs.existsSync(xmlDir)) {
        fs.mkdirSync(xmlDir, { recursive: true });
      }

      const backupPath    = path.join(xmlDir, 'secure_store_backup_rules.xml');
      const extractPath   = path.join(xmlDir, 'secure_store_data_extraction_rules.xml');

      // Only write if the file doesn't already exist (idempotent)
      if (!fs.existsSync(backupPath)) {
        fs.writeFileSync(backupPath, BACKUP_RULES, 'utf8');
      }
      if (!fs.existsSync(extractPath)) {
        fs.writeFileSync(extractPath, EXTRACTION_RULES, 'utf8');
      }

      return mod;
    },
  ]);
};
