import React, { useCallback, useEffect, useState } from 'react';
import {
  FlatList,
  Pressable,
  ScrollView,
  StyleSheet,
  Text,
  View,
} from 'react-native';
import Animated, {
  useSharedValue,
  useAnimatedStyle,
  withTiming,
} from 'react-native-reanimated';
import { Ionicons } from '@expo/vector-icons';
import { SignalCard } from '../../components/SignalCard';
import { SkeletonCard } from '../../components/SkeletonCard';
import { LiveDot } from '../../components/LiveDot';
import { useSignalStore } from '../../store/signalStore';
import { useAccountStore } from '../../store/accountStore';
import { signalService } from '../../services/signalService';
import { COLORS, FONTS, RADIUS, SPACING } from '../../theme';
import type { Signal } from '../../store/signalStore';

type FilterType = 'All' | 'BUY' | 'SELL' | 'Active';
const FILTERS: FilterType[] = ['All', 'BUY', 'SELL', 'Active'];

export const SignalsScreen: React.FC = () => {
  const { signals, setSignals, markExpiredSignals, isLoading, setLoading, setError, error } =
    useSignalStore();
  const { accounts } = useAccountStore();

  const [activeFilter, setActiveFilter] = useState<FilterType>('All');

  const hasAutomatedAccount = accounts.some((a) => a.subscriptionMode === 'automated_trading');

  // Header animation
  const headerOpacity = useSharedValue(0);
  useEffect(() => {
    headerOpacity.value = withTiming(1, { duration: 400 });
  }, []);
  const headerAnimStyle = useAnimatedStyle(() => ({ opacity: headerOpacity.value }));

  const loadSignals = useCallback(async () => {
    setLoading(true);
    setError(null);
    try {
      const data = await signalService.getSignals({ limit: 50 });
      setSignals(data);
      markExpiredSignals();
    } catch {
      setError('Failed to load signals');
    } finally {
      setLoading(false);
    }
  }, [setSignals, markExpiredSignals, setError, setLoading]);

  useEffect(() => {
    void loadSignals();
    const interval = setInterval(() => { markExpiredSignals(); }, 60_000);
    return () => clearInterval(interval);
  }, [loadSignals, markExpiredSignals]);

  const filteredSignals = signals.filter((s: Signal) => {
    if (activeFilter === 'All') return true;
    if (activeFilter === 'BUY') return s.direction === 'BUY';
    if (activeFilter === 'SELL') return s.direction === 'SELL';
    if (activeFilter === 'Active') return s.status !== 'expired';
    return true;
  });

  const activeCount = signals.filter((s) => s.status !== 'expired').length;

  const renderSignal = ({ item, index }: { item: Signal; index: number }) => {
    const account = accounts.find((a) => a.accountId === item.userAccountId);
    const isAutomated = account?.subscriptionMode === 'automated_trading' || hasAutomatedAccount;
    return <SignalCard signal={item} isAutomatedAccount={isAutomated} index={index} />;
  };

  const ListEmpty = () => (
    <View style={styles.emptyState}>
      <Ionicons name="radio-outline" size={48} color={COLORS.textMuted} />
      <Text style={styles.emptyTitle}>Waiting for signals...</Text>
      <Text style={styles.emptySubtitle}>
        Real-time signals will appear here as they are generated by the AI.
      </Text>
    </View>
  );

  return (
    <View style={styles.container}>
      {/* Header */}
      <Animated.View style={[styles.headerRow, headerAnimStyle]}>
        <View>
          <Text style={styles.screenTitle}>Signals</Text>
          {activeCount > 0 && (
            <View style={styles.liveRow}>
              <LiveDot size={6} />
              <Text style={styles.liveText}> {activeCount} active</Text>
            </View>
          )}
        </View>
        {signals.length > 0 && (
          <Text style={styles.totalCount}>{signals.length} total</Text>
        )}
      </Animated.View>

      {/* Filter chips */}
      <ScrollView
        horizontal
        showsHorizontalScrollIndicator={false}
        style={styles.filterScroll}
        contentContainerStyle={styles.filterContent}
      >
        {FILTERS.map((f) => (
          <Pressable
            key={f}
            style={[styles.filterChip, activeFilter === f && styles.filterChipActive]}
            onPress={() => setActiveFilter(f)}
          >
            <Text style={[styles.filterChipText, activeFilter === f && styles.filterChipTextActive]}>
              {f}
            </Text>
          </Pressable>
        ))}
      </ScrollView>

      {error && (
        <View style={styles.errorBanner}>
          <Text style={styles.errorText}>{error}</Text>
        </View>
      )}

      {isLoading ? (
        <>
          <SkeletonCard />
          <SkeletonCard />
          <SkeletonCard />
        </>
      ) : (
        <FlatList
          data={filteredSignals}
          keyExtractor={(item) => item.signalId}
          renderItem={renderSignal}
          ListEmptyComponent={<ListEmpty />}
          contentContainerStyle={styles.listContent}
          onRefresh={loadSignals}
          refreshing={isLoading}
        />
      )}
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.bg,
  },
  headerRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    paddingHorizontal: SPACING.md,
    paddingTop: 20,
    paddingBottom: 8,
  },
  screenTitle: {
    color: COLORS.text,
    fontSize: FONTS.sizes['3xl'],
    fontWeight: FONTS.weights.extrabold,
  },
  liveRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 4,
  },
  liveText: {
    color: COLORS.primary,
    fontSize: FONTS.sizes.xs,
    fontWeight: FONTS.weights.semibold,
  },
  totalCount: {
    color: COLORS.textSecondary,
    fontSize: FONTS.sizes.sm,
    alignSelf: 'flex-end',
    marginBottom: 4,
  },
  filterScroll: {
    flexGrow: 0,
    marginBottom: 8,
  },
  filterContent: {
    paddingHorizontal: SPACING.md,
    gap: 8,
    paddingBottom: 4,
  },
  filterChip: {
    paddingHorizontal: 16,
    paddingVertical: 7,
    borderRadius: RADIUS.full,
    borderWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: COLORS.bgCard,
  },
  filterChipActive: {
    borderColor: COLORS.primary,
    backgroundColor: COLORS.primaryLight,
  },
  filterChipText: {
    color: COLORS.textSecondary,
    fontSize: FONTS.sizes.sm,
    fontWeight: FONTS.weights.medium,
  },
  filterChipTextActive: {
    color: COLORS.primary,
    fontWeight: FONTS.weights.bold,
  },
  errorBanner: {
    backgroundColor: 'rgba(255,59,92,0.1)',
    marginHorizontal: SPACING.md,
    borderRadius: RADIUS.sm,
    padding: 10,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: COLORS.error,
  },
  errorText: {
    color: COLORS.error,
    fontSize: FONTS.sizes.sm,
    textAlign: 'center',
  },
  listContent: {
    paddingBottom: 20,
    flexGrow: 1,
  },
  emptyState: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 32,
    paddingTop: 80,
  },
  emptyTitle: {
    color: COLORS.text,
    fontSize: FONTS.sizes.xl,
    fontWeight: FONTS.weights.bold,
    marginBottom: 8,
    marginTop: 16,
  },
  emptySubtitle: {
    color: COLORS.textSecondary,
    fontSize: FONTS.sizes.sm,
    textAlign: 'center',
    lineHeight: 20,
  },
});
